version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - volume-db:/var/lib/mysql

volumes:
  volume-db: